version: "3.8"

services:
  test-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 8881:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
